version: '3.4'
services:
  database:
    image: postgres:9.5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD:
      POSTGRES_USER: surveydonkey
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    volumes:
      - ./cicd/flyway/flyway.conf:/flyway/conf/flyway.conf
      - .:/app
    working_dir: /app

  python:
    image: lambci/lambda:build-python3.6
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app

