AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: the type of environment
    AllowedValues:
      - dev
      - int
      - stating
      - prod
  AppName:
    Type: String
  ServiceName:
    Type: String
  ServiceVersion:
    Type: String
    Default: v1
  S3Dir:
    Type: String


Resources:
  DefaultLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-${Environment}-${ServiceName}-DefaultLambdaExecutionRole-${ServiceVersion}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - sts:AssumeRole

  DefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${AppName}-${Environment}-${ServiceName}-DefaultPolicy-${ServiceVersion}'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "*"
            Resource: "*"
      Roles:
        - Ref: "DefaultLambdaExecutionRole"

  GreetingFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'Greeting'
      Description: 'say hello to users'
      MemorySize: 128
      Timeout: 30
      Runtime: python3.6
      Code:
        S3Bucket: jamesni-cloudformation-demo-2019
        S3Key: !Sub '${S3Dir}/cf-demo.zip'
      Role:
        Fn::GetAtt:
          - "DefaultLambdaExecutionRole"
          - "Arn"
      Handler: 'handlers/greeting.handler'



